-- MentorSetu reproducible setup for SQL*Plus (run as system).
-- Each step is a separate sqlplus call because the scripts EXIT on completion:
--
--   sqlplus system/admin@//localhost:1521/XEPDB1 @db/oracle_schema.sql
--   sqlplus system/admin@//localhost:1521/XEPDB1 @db/oracle_seed.sql
--   sqlplus system/admin@//localhost:1521/XEPDB1 @db/migrate_02_feedback.sql
--
-- Verify with:
--   sqlplus system/admin@//localhost:1521/XEPDB1 @db/verify_queries.sql
--   sqlplus system/admin@//localhost:1521/XEPDB1 @evidence/database/verify.sql
--
-- Reset = re-run oracle_schema.sql (it drops objects first), then seed + migration.
-- Demo logins (password Password123!): student1@college.edu, alumni1@example.com,
-- coordinator@college.edu. All data is synthetic.
